workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk --release --dart-define=OPENAI_KEY=$OPENAI_KEY
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
